from . import customer, exams, guardrails, health, jev, language, legal, news, politics, retrieval, safety, seeds, tools

SOURCES = {
    "tc32": customer.build_tc32,
    "google_maps": customer.build_google_maps,
    "yemeksepeti": customer.build_yemeksepeti,
    "trendyol": customer.build_trendyol,
    "vitamins": customer.build_vitamins,
    "absa": customer.build_absa,
    "product_category": customer.build_product_category,
    "lavoir": customer.build_lavoir,
    "hatemap": safety.build_hatemap,
    "hate_superset": safety.build_hate_superset,
    "offensive_nanelimon": safety.build_offensive_nanelimon,
    "offensive_eymaahner": safety.build_offensive_eymaahner,
    "harmful_tweets": safety.build_harmful_tweets,
    "spam_email_aydemir": safety.build_spam_email_aydemir,
    "spam_email_orvile": safety.build_spam_email_orvile,
    "spam_sms": safety.build_spam_sms,
    "fraud_gambling": safety.build_fraud_gambling,
    "guardrail": guardrails.build_guardrail,
    "guardrail_translated": guardrails.build_guardrail_translated,
    "injection": guardrails.build_injection,
    "webfaq": retrieval.build_webfaq,
    "tools_when2call": tools.build_tools_when2call,
    "tools_atasoglu": tools.build_tools_atasoglu,
    "tools_hermes": tools.build_tools_hermes,
    "facturk": news.build_facturk,
    "interpress": news.build_interpress,
    "kemik_news": news.build_kemik_news,
    "bilcat": news.build_bilcat,
    "tremo": news.build_tremo,
    "wiki_stance": politics.build_wiki_stance,
    "court_outcome": legal.build_court_outcome,
    "doktorsitesi": health.build_doktorsitesi,
    "thesis": exams.build_thesis,
    "trglue": language.build_trglue,
    "gecturk": language.build_gecturk,
    "plu_steps": language.build_plu_steps,
    "open_jev": jev.build_open_jev,
    "yorumbudur": seeds.build_yorumbudur,
    "financial_news": seeds.build_financial_news,
    "kap": seeds.build_kap,
    "thy_tweets": seeds.build_thy_tweets,
    "tr_news": seeds.build_tr_news,
    "parliament": seeds.build_parliament,
    "wikipedia": seeds.build_wikipedia,
}
